# Default values for letoii chart

scraper:
  image:
    repository: ghcr.io/kalenpeterson/letoii/scraper
    tag: latest
    pullPolicy: IfNotPresent
  schedule: "0 0 * * *" # Daily at midnight
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env: []
  # - name: EXAMPLE_VAR
  #   value: "example-value"

  # Optional volume mounts
  volumes: []
  volumeMounts: []

minio:
  enabled: true
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  mode: standalone
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 250m
      memory: 512Mi
  accessKey: minioadmin
  secretKey: minioadmin
  service:
    type: ClusterIP
    port: 9000
  consoleService:
    type: ClusterIP
    port: 9001
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: minio.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
