{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-creds
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-minio
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc }}
  secretKey: {{ .Values.minio.secretKey | b64enc }}
{{- end }}