{{- if and .Values.minio.enabled .Values.minio.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-minio-console
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-minio-console
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.minio.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.minio.ingress.tls }}
  tls:
    {{- range .Values.minio.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.minio.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-minio-console
                port:
                  number: {{ $.Values.minio.consoleService.port }}
          {{- end }}
    {{- end }}
{{- end }}